import { OriginLeaf, leaf_handler} from "../src/leaf_handler/src/leaf_handler"
import { RLP } from '@ethereumjs/rlp'
import { v4 as uuidv4, parse as uuidParse} from 'uuid';

const BN = require("bn.js");
// the rlp_code of "zcloak" is  [134, 122, 99, 108, 111, 97, 107]
let string_zcloak_u8a = RLP.encode("zcloak");
// the rlp_code of 22 is  [22]
let number_22_u8a = RLP.encode(22);


// generated by uuidv4()
let uuid_1 = "505e3652-18ff-487e-aab2-6abad9100ce5";
let uuid_2 = "6a918fb8-8f87-4d87-8a5d-15f1eddfbe92";
let uuid_1_parse = uuidParse(uuid_1);
let uuid_2_parse = uuidParse(uuid_2);

// saltedhashes are : 33fc8bc7a40bdcab80cd15a330dd9f09df22c828e16e69d8ca8846fb68f171cd, b8d9cfeb9626dc91f92af02de3253c8d0c08d5e009138c5e6d59c918c5d56064

let originleaves: OriginLeaf[] = [
    // index -- start with 0
    {index:1, rlp: string_zcloak_u8a, uuid: Uint8Array.from(uuid_1_parse)},
    {index:0, rlp: number_22_u8a, uuid:  Uint8Array.from(uuid_2_parse)}
];

let roothash = leaf_handler(originleaves);
// roothash is bc5a29b2e6cba18835f22d4e6e20c7c250cc01b902451df8163df9b7f00244e2
console.log(roothash)